name: Release

# Run workflow on commits to the `master` branch
on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: test
        run: |
          ls
          ls -a ~ 
          ls ~/.m2
          cat ~/.m2/settings.xml

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
